### ISSUE TITLE
What training set do you use?

### ISSUE THREAD

**Issue by wangbq18** [sodawater/RoleLabel#1]

**Comment by sodawater** [comment]
Sorry, I can't remember. It was just a class project a few years ago.

**Comment by wangbq18** [comment]
thank for you reply, do you remember the data format?

**Comment by sodawater** [comment]
source: Text and POStag    target:  Semantic Role Label

Text: 希望 你们 本 着 爱 国 爱 港 的 精神 ， 认真 贯彻 执行 基本法 ， 恪尽职守 ， 不负众望 。
POStag: VV PN VV AS VV NN VV NR DEC NN PU AD VV VV NN PU VV PU VV PU
SRL: O O O O O O rel ARG1 O O O O O O O O O O O O

(ps: this repository is unfinished and there might be many mistakes in the code)
